# -*- coding: utf-8 -*-
"""5.8 - Acréscimo de variáveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XrCQI_3d8rDVds2qRlDtQAXv_x2cZwk
"""

import pandas as pd
import datetime as dt

#le o arquivo CSV
df = pd.read_csv("df_OVNI_limpo.csv", index_col=[0])

print("Dividir o conteúdo da coluna Date / Time em duas novas colunas no mesmo dataframe e deletar a coluna Date / Time .")

#converte a coluna Data/Time que era string para o tipo datetime
df['Date / Time'] = pd.to_datetime(df['Date / Time'])

#cria uma nova coluna Sight_Date que recebera so a data no formato de string
df['Sight_Date'] = df['Date / Time'].dt.strftime('%m/%d/%Y')
#cria uma nova coluna Sight_Time que recebera a hora no formato de string
df['Sight_Time'] = df['Date / Time'].dt.strftime('%H:%M')
#exclui a coluna Data/Time
df = df.drop(columns=['Date / Time'])

#plota o dataframe
df

print("Fazer o mesmo procedimento para dias da semana. Será que existe um dia da semana com mais ocorrências de relatórios para OVNIs? Para descobrir isso, você deve criar uma nova coluna chamada weekdays.")

#converte o tipo da coluna Sight_Date para datetime
df['Sight_Date'] = pd.to_datetime(df['Sight_Date'])

#cria um array com os nomes da semana em portugues
dias = ['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo']

#criar uma nova coluna Sight_weekday que recebe os dias da semana representados por numeros de 0 a 6
df['Sight_Weekday'] = df['Sight_Date'].dt.dayofweek

#cria um for que insere o nome de todos os dias da semana baseado no indice do vetor no qual sera fornecido pela coluna criada acima
for i in df.itertuples():
  df.Sight_Weekday[i.Index] = dias[df.Sight_Weekday[i.Index]]

#plota o dataframe
df

print("Separar as variáveis mês (Month) e dia (Day). Desse modo, será possível refinar as pesquisas.")

#cria uma nova coluna Sight_Day na qual recebe o dia separado da data
df['Sight_Day'] = df['Sight_Date'].dt.day
#cria uma nova coluna Sight_Month na qual recebe o mes separado da data
df['Sight_Month'] = df['Sight_Date'].dt.month

#plota o dataframe
df

print("Por fim, salvar o dataframe resultante em um arquivo .csv com o nome: 'df_OVNI_preparado'.")

#gera arquivo CSV
df.to_csv("df_OVNI_preparado.csv")