# -*- coding: utf-8 -*-
"""Concatenador de Longitude e Latitude.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAlKqsGS1WEZZyq6_aGiYH3xpV05o7xL
"""

#O objetivo deste algoritmo é gerar um CSV de todas os relatos dos estados dos EUA 
#com duas respectivas latitudes e longitudes
import pandas as pd

#lê o arquivo csv com os relatos
df_ovnis = pd.read_csv("ovnis.csv", index_col=[0])
#lê o  arquivo csv com todas latitudes e longitudes dos estados
df_longlat = pd.read_csv("uscities.csv")

#inicias os arrays
cidades = []
lats = []
lngs = []

#adicionas aos arrays todas cidades, latitudes e longitudes com os mesmos index
for i, row in df_longlat.iterrows():
  cidades.append(row["city"])
  lats.append(row["lat"])
  lngs.append(row["lng"])

print("Carregou todas as cidades, longitudes e latitudes")

#Array contendo as siglas de  todos os estados dos EUA
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

selection = df_ovnis['State'].isin(states)
#Dataframe ja filtrado com estados so dos EUA
df_eua = df_ovnis[selection]

#Prepara novas colunas para o novo dataframe
COLUNAS = [
    'City',
    'State',
    'Latitude',
    'Longitude'
]

#cria novo dataframe concatenado
df_cidades = pd.DataFrame(columns=COLUNAS)
#adiciona suas respectivas  colunas
df_cidades['City'] = df_eua['City']
df_cidades['State'] = df_eua['State']

#funcao que retorna a latitude de acordo com o nome da cidade
def getLatitude(city):
  latitude = 0
  for i in range(0, len(cidades)):
    if(city == cidades[i]):
      latitude = lats[i]
  return latitude

#funcao que retorna a longitude de acordo com o nome da cidade
def getLongitude(city):
  longitude = 0
  for i in range(0, len(cidades)):
    if(city == cidades[i]):
      longitude = lngs[i]
  return longitude

#Incrementa o valor da latitude e longitude de cada linha do dataframe
for i in range(0, len(df_cidades)):
  df_cidades.iloc[i].Latitude = getLatitude(df_cidades.iloc[i].City)
  df_cidades.iloc[i].Longitude = getLongitude(df_cidades.iloc[i].City)

#gera CSV concatenado
df_cidades.to_csv("ovnis_lat_lng.csv")
#ESSE PROCESSO PODE DEMORAR BASTANTE, POIS SÃO MUITAS CIDADES
df_cidades