# -*- coding: utf-8 -*-
"""[DEF] 5.4 - Exploração dos dados com SQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_F2lBxZ48FPGLvCGTkRpKXeCONP9qv7
"""

import pandas as pd

df_ovnis = pd.read_csv("ovnis.csv", index_col=[0])

print("1. Quantidade de variáveis que foram coletadas:")
#Conta a quantidade de vdados para cada variavel com a funcao count()
df_ovnis.count()

print("2. Relatos que ocorreram por estado em ordem decrescente:")
#Usa a funcao groupby() pra agrupar por estado, a funcao count() para contar e a funcao sort_values() para ordenar de forma decrescente
df_relatos = df_ovnis
df_relatos = df_relatos.groupby('State').count()
df_relatos = df_relatos.sort_values(ascending=False, by="Posted")['Posted']
df_relatos

print("3. Remover possíveis campos vazios (sem estado):")
#Exclui toda linha cujo Estado seja nulo com a funcao dropna()
df_ovnis = df_ovnis.dropna(subset=["State"])
df_ovnis

print("4. Limitar a análise aos estados dos Estados Unidos.")

#como a planilha nao oferece dados dos paises de origem, o vetor abaixo representa a sigla dos estados dos EUA
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

selection = df_ovnis['State'].isin(states)
df_ovnis = df_ovnis[selection]

df_ovnis

print("5. Consulta por cidades, com o objetivo de saber quais contêm o maior número de relatos (cidades que apresentem ao menos 10 relatos).")

#Usa a funcao groupby() pra agrupar por estado, a funcao count() para contar e a funcao sort_values() para ordenar de forma decrescente
cidades = df_ovnis
cidades = cidades.groupby('City').count()
cidades = cidades.sort_values(ascending=False, by="Posted")
cidades = cidades.query('Posted >= 10')['Posted']
cidades

print("6. Com o dado anterior, responder a seguinte pergunta: por que será que essa é a cidade que possui mais relatos?")
print("Porque é a cidade onde fica mais afastada de grandes metrópoles, construída no local de antigos canais indigenas")

print("7. Fazer uma query exclusiva para o estado com maior número de relatos, buscando cidades que possuam um número superior a 10 relatórios. Enfatizar a cidade, a quantidade de relatos e formato do objeto não identificado.")

california = df_ovnis[df_ovnis['State']=='CA']

COLUNAS = [
    'City',
    'Shape',
    'Quantidade'
]

df_final = pd.DataFrame(columns=COLUNAS)
df_final['City'] = california['City']
df_final['Shape'] = california['Shape']
df_final['Quantidade'] = california.groupby('City')['City'].transform('count')

#gera arquivo .csv
df_final.to_csv("ovnis_maiores_relatos.csv")

df_final